services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5469:5432"
    volumes:
      - ./pgDatabase/on_start:/docker-entrypoint-initdb.d
      - ./pgDatabase/data:/data
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pgnet

  csvloader:
    image: python:3.13-slim
    depends_on:
      - postgres
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y --no-install-recommends git &&
        pip install uv &&
        uv venv &&
        uv pip install git+https://github.com/ThriveAI-Solutions/db_discovery_lib.git &&
        uv run db-discovery-lib --db-name postgres --username postgres --password postgres --host localhost --port 5432
      "
    networks:
      - pgnet

volumes:
  postgres_data:
    driver: local

networks:
  pgnet:
    driver: bridge
