[ai_keys]
### OPTIONAL ###
## Default Vanna functionality ##
# vanna_api = ""
# vanna_model = ""
## Open AI - Fallback to LLM feature ##
# openai_api = ""
# openai_model = "gpt-4o"
## Open Router Values for Anthropic ##
# anthropic_api = ""
# anthropic_model = "claude-3-5-sonnet-latest"
## Local ollama install required ##
# ollama_host = "http://localhost:11434"
# ollama_model = "llama3.2"

[rag_model]
### OPTIONAL ###
## ChromaDB Configuration for local RAG storage##
# chroma_path = "./chromadb"

[security]
allow_llm_to_see_data = 'False'

[cookie]
password = ""

[postgres]
host = "localhost"
port = 5433
database = ""
user = ""
password = ""
