[ai_keys]
# openai_api = ""
# openai_model = "gpt-4o"
vanna_api = ""
vanna_model = ""
# anthropic_api = ""
# anthropic_model = "claude-3-5-sonnet-latest"

[cookie]
password = ""

[postgres]
host = "localhost"
port = 5433
database = ""
user = ""
password = ""
